dependencies:
- name: elasticsearch
  version: "7.3.0"
  repository: https://helm.elastic.co
- name: fluent-bit
  version: "1.3.0"
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: fluent-bit.enabled
- name: kibana
  version: "7.3.0"
  repository: https://helm.elastic.co
- name: filebeat
  version: "7.3.0"
  repository: https://helm.elastic.co
  condition: filebeat.enabled
