dependencies:
- name: elasticsearch
  version: "7.2.0"
  repository: https://helm.elastic.co
- name: fluent-bit
  version: "1.3.0"
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: kibana
  version: "7.2.0"
  repository: https://helm.elastic.co
