# Default values for efk.

# https://github.com/elastic/helm-charts/blob/master/kibana/values.yaml
kibana:
  elasticsearchURL: "" # "http://elasticsearch-efk-master:9200"
  elasticsearchHosts: "http://elasticsearch-efk-master:9200"

# https://github.com/elastic/helm-charts/blob/master/elasticsearch/values.yaml
elasticsearch:
  clusterName: "elasticsearch-efk"
  nodeGroup: "master"

  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 5Gi

  persistence:
    enabled: true

# https://github.com/helm/charts/blob/master/stable/fluent-bit/values.yaml
fluent-bit:
  enabled: false
  image:
    fluent_bit:
      repository: fluent/fluent-bit
      tag: 1.2.2
    pullPolicy: IfNotPresent
  backend:
    type: es
    es:
      host: elasticsearch-efk-master
      port: 9200
      index: kubernetes_cluster
      logstash_prefix: kubernetes_cluster

filebeat:
  enabled: false
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
      - type: docker
        containers.ids:
        - '*'
        processors:
        - add_kubernetes_metadata:
            in_cluster: true

      output.elasticsearch:
        hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-efk-master:9200}'

      filebeat.modules:
        - module: kafka
        - module: system
